# chasten configuration
# used for testing purposes
chasten:
  # point to a combination of checks files and local files
  checks-file:
    - https://raw.githubusercontent.com/AstuteSource/chasten-configuration/master/dummy_checks.yml
    - checks.yml
    - https://raw.githubusercontent.com/AstuteSource/chasten-configuration/master/dummy_checks.yml
    - checks.yml
